language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

install:
  # Install flagen in env
  - "pip install -e ."

  # Build/test dependencies
  - "pip install -r dev_requirements.txt"

# command to run tests
script:
  # Tests
  - tox

after_success:
  - codecov
